language: python
matrix:
    include:
        - python: 2.7
          dist: trusty
          sudo: false
        - python: 3.4
          dist: trusty
          sudo: false
        - python: 3.5
          dist: trusty
          sudo: false
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: bionic
          sudo: true
        - python: 3.7
          dist: artful
          sudo: true
        - python: 3.7
          dist: rawhide
          sudo: true
        - python: 3.7
          dist: stretch
          sudo: true
        - python: 3.7
          dist: jessie
          sudo: true
# command to install dependencies
install:
  - pip install tox-travis
  - pip install pytest
  - pip install -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - tox # or py.test for Python versions 3.5 and below